version: '3'
services:
  bridge:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: DuhItsJay/Guild-Chat-Bridge
    environment:
      SERVER_HOST: mc.hypixel.net
      SERVER_PORT: 25565
      MINECRAFT_USERNAME: yourUsername
      MINECRAFT_PASSWORD: yourPassword
      MINECRAFT_LOBBY_HOLDER: lobbyHolder
      MINECRAFT_ACCOUNT_TYPE: mojang
      DISCORD_TOKEN: yourDiscordToken
      DISCORD_GUILD_CHANNEL: discordChannelId
		  DISCORD_OFFICER_CHANNEL: discordChannelId
		  DISCORD_COMMAND_ROLE: discordCommandRoleId
		  DISCORD_OWNER_ID: discordCommandRoleId or discordOwnerId
		  MESSAGE_MODE: bot
		  API_KEY: apiKey
		  AUTO_REPLACE_KEY: false